<a href="https://colab.research.google.com/github/AnshulKanwar/8-puzzle-problem/blob/main/102016080.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [45]:
!pwd

/content


# Creating Data File

In [43]:
data = np.random.randint(0, 100, size=(65000, 10000))

In [44]:
np.save("data.npy", data)

# Load File

In [ ]:
data = np.load("data.npy")

# Lab Assignment 2

1. Create a data file by using python random module with different random generator parameters. The data file must have 65000 X 10000 (rows X columns) in the data file. This data file to be used as database for realization of math and matrix operations in cloud computing lab assignments.

2. Write a program to assign subsequent rows to matrix first row elements.

3. Write a program in python to group similar elements into matrix

4. Write a program in Python to add and subtract matrices

5. Write a program in Python to create a nxn square matrix, where all the sub-matrix has the sum of opposite corner elements as even

6. Write a program in Python to perform row-wise element addition in tuple matrix

In [ ]:
a=np.random.randint(1,100,size=(5,4))
a

array([[33, 74, 83, 30],
       [24, 60, 98, 14],
       [55, 56, 72, 85],
       [64, 33, 36, 28],
       [81, 14, 88, 74]])

In [ ]:
di={}
# di[-1]=[1,2]
temp=[]
num=0
for i in a:
  k=0
  for j in i:
    
   
    if(k==0):
      num=j
      k=1
      continue
    temp.append(j)
    # print(temp)
  di[num]=temp.copy()
  # print(di)
  temp.clear()

di

In [ ]:
li=[1,1,1,2,2,2,3,4,3,2,2,4,5,6]
ls=sorted(li)
final=[]
j=0
for i in range(len(ls)-1):
  if(i<j):
    continue
  while(ls[j]==ls[i]):
    j=j+1
  q=j-i
  # print(f"q is {q}")
  temp=[]
  while(q!=0):
    temp.append(ls[i])
    q=q-1
  # print(temp)
  i=j+1
  # print(i,j)
 
  final.append(temp.copy())
  temp.clear()
  # print(final)
final

[[1, 1, 1], [2, 2, 2, 2, 2], [3, 3], [4, 4], [5]]

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])

print("Addition of two matrix")
print(np.add(A, B))

Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [ ]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])  
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
n=4
p=1
evdiag=np.zeros((n,n),dtype=np.int32)
if(n%2==0):
   for i in range(n):
    for j in range(n):
      evdiag[i,j]=p
      p=p+1
    i=0
    j=0
    # print(evdiag)
   for i in range(n):
      if(i%2==0):
        continue
      else:
        temp=evdiag[i].copy()
        for j in range(n):
          
         evdiag[i][n-j-1]=temp[j]
        # print(temp)

          

else:
  
  for i in range(n):
    for j in range(n):
      evdiag[i,j]=p
      p=p+1
evdiag

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12],
       [16, 15, 14, 13]], dtype=int32)

In [ ]:
# res = [[sub + (cus_eles[idx], ) for sub in val] for idx, val in enumerate(test_list)]
# read enumerate function

In [ ]:
lo=[1,2,3,4]
lo[len(lo)-1]

4

# Lab Assignment 3

In [ ]:
l = data[1]

1. Write a python program to sum all the elements in a list

In [ ]:
sum(l)

495926

(2) Write a Python program to get the largest number from a list.

In [ ]:
max(l)

99

(3) Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples

In [ ]:
list_of_tuples = [(1,3,4),
                  (9,1,7),
                  (5,8,2)]

sorted(list_of_tuples, key=lambda x: x[-1])

[(5, 8, 2), (1, 3, 4), (9, 1, 7)]

(4) Write a Python program to remove duplicates from a list

In [ ]:
print(set(l))

(5) Write a Python program to find the list of words that are longer than n from a given list of words

In [ ]:
n = 3
words = ["abc", "baqsda", "s", "bsed", "rf", "asdf", "agamjot"]

words_longer_than_n = [word for word in words if len(word) > n]
print(words_longer_than_n)

['baqsda', 'bsed', 'asdf', 'agamjot']


(6) Write a Python program to get the difference between the two lists

In [ ]:
l2 = data[2]

difference = [i-j for (i, j) in zip(l, l2)]
print(difference)

[-60, -14, 94, 48, 36, 83, -2, -9, -4, -36, -2, 67, -63, 4, 13, 4, 79, -14, 19, 6, -73, -76, 42, -15, -64, -14, 60, -48, 78, 54, -64, -75, 57, 9, -6, 45, -71, -3, 30, 27, -19, -26, 20, -10, 44, 4, -42, 21, 47, 87, 83, -23, 25, -41, 50, 14, 14, -3, -12, -46, -82, 42, -21, 82, 3, 5, -83, 82, -3, 22, 7, -41, 13, 20, 42, 67, -72, -4, -33, -25, 19, -76, -28, 65, 99, -49, -22, -8, -34, -25, -14, -20, 44, -59, 12, 42, -52, -38, -6, -22, -1, 12, -85, -30, 44, 11, -1, 14, 16, 3, -63, 35, 40, 76, 30, 7, -23, 35, 43, -68, -12, -40, -5, 94, -5, 68, -8, -61, -65, -6, 64, 22, 47, -34, -2, -27, -13, -54, 39, -10, -37, -37, 28, 42, -12, -44, 15, -72, 67, 42, 50, 18, 23, -60, -28, 14, -41, -40, 59, 39, -64, 10, 30, -17, 65, -54, -55, -29, -12, -37, -17, -3, 79, -97, -46, 76, -12, 32, -43, -28, -90, -25, 1, -1, 45, 8, -44, -45, -63, -70, -32, 55, 17, -66, 38, 52, 44, -6, -35, -10, -65, 28, -23, 95, -24, -4, 91, -1, -85, -20, -51, 15, 4, -67, -8, -16, -40, 91, 14, -4, -49, -66, -10, -24, 15, 44, 33, -40,

(7) Write a Python script to add a key to a dictionary

In [ ]:
dic = {'India': 'Delhi',
       'France': 'Paris',
       'Australia': 'Canberra'}
  
dic['Russia'] = 'Moscow'

print(dic)

{'India': 'Delhi', 'France': 'Paris', 'Australia': 'Canberra', 'Russia': 'Moscow'}


(8) Write a Python script to concatenate following dictionaries to create a new one.


```python
dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}
```

Expected Result: `{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}`


In [ ]:
dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}

dic4 = {}
dic4.update(dic1)
dic4.update(dic2)
dic4.update(dic3)
print(dic4)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


(9) Write a Python program to remove a key from a dictionary

In [ ]:
dic = {'India': 'Delhi',
       'France': 'Paris',
       'Australia': 'Canberra'}

dic.pop('France')
print(dic)

{'India': 'Delhi', 'Australia': 'Canberra'}


(10) Write a Python program to multiply all the items in a dictionary

In [ ]:
dic = {'one': 1,
       'two': 2,
       'three': 3,
}

mul = 1
for i in dic.values():
  mul = mul * i

print(mul)

6
